version 2.1

workflows:
  version: 2
  testing-workflow:
    jobs: 
      - build:
          context: testing
          filters:
            branches:
              only:
                - develop

jobs:
  build:
    docker:
      - image: cimp/base:stable
    steps:
      - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_ACCOUNT_URL
        create-repo: false
        dockerfile: Dockerfile
        region: AWS_DEFAULT_REGION
        repo: $AWS_ECR_REPO_NAME
        tag: "latest.$(git rev-parse HEAD)"

orbs:
  slack: circleci/slack@4.6.0
  kubernetes: circleci/kubernetes@1.3.0
  awk-eks: circleci/pws-eks@1.1.0
  helm: circleci/helm@1.1.0
  aws-ecr: circleci/aws-ecr@8.9.0